name: Build
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Compile
      run: make release -j$(nproc)
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v4
      with:
        name: Linux
        path: build/*.zip

  windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        choco install zip
        make release -j $env:NUMBER_OF_PROCESSORS
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v4
      with:
        name: Windows
        path: build/*.zip

  windows-x86:
    name: Windows-x86
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Install zip
        run: choco install zip -y
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          install: |
            mingw-w64-i686-gcc
            make
      - name: Compile
        shell: msys2 {0}
        run: |
          make ARCH=x86 WINDRES="windres -F pe-i386" -j $(nproc)
        env:
          ARCHIVE: 1
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-x86
          path: build/*.zip
  macos:
    name: macOS
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: make release -j$(sysctl -n hw.logicalcpu)
      env:
        ARCHIVE: 1
    - uses: actions/upload-artifact@v4
      with:
        name: macOS
        path: build/*.zip

  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: emscripten-core/emsdk
        path: emsdk
    - name: Install Dependencies
      run: |
        cd emsdk
        ./emsdk install 3.1.58
        ./emsdk activate 3.1.58
    - name: Compile
      env:
        ARCHIVE: 1
      run: |
        source emsdk/emsdk_env.sh
        emmake make release -j$(nproc)
    - uses: actions/upload-artifact@v4
      with:
        name: Web
        path: build/*.zip
